#!/bin/bash

# Copyright (C) 2009-2012 The PISM Authors
##################################################################################
# Spinup of PISM trunk (tested for revision 1844) using Data from Anne Le Brocq (from SeaRISE wiki)...
#...with PIK physics (winkelmann_martin11), mostly as described in martin_winkelmann11 but with enthalpy model and modified configuration parameters
#...with constant climate, using constant Precip and a parameterization for artm as in martin_winkelmann11
#... WARNING: especially for the last part, where finer resolutions are run, output is large!
##################################################################################

echo "(antspinCC.sh)   run preprocess.sh before this..."
#inputs generated by preprocess.sh:   	present day: pism_Antarctica_5km.nc 
#					glacial cycle spinup: pism_dT.nc pism_dSL.nc
#					future climate data:  ar4_ant_acab_anomaly_scalefactor_1.0.nc (as well as scalefactors 1.5 and 2.0)
#							      ar4_ant_artm_anomaly_scalefactor_1.0.nc (as well as scalefactors 1.5 and 2.0)

set -e  # exit on error

echo "(antspinCC.sh)   Constant-climate spinup-script using SeaRISE-Antarctica data and -ssa_sliding and -pik"


experiment=seaRISE
version=pism-dev
scriptname=spinupStSt
laufname=ConstantClimate
output_path=./results/$experiment/$scriptname/$laufname


# naming directories
RESDIR=$output_path/results/ 
OUTDIR=$output_path/output/ 
CODE_DIR=../../bin
BOOTDIR=.

# naming files
SCRIPTNAME="antspinCC.sh"
PISM_EXEC=$CODE_DIR/pismr
# for echo:
PISM_EXEC="$CODE_DIR/pismr"
echo "$SCRIPTNAME       PISM_EXEC = $PISM_EXEC"

# creating directories for results
mkdir -p $output_path/results
mkdir -p $output_path/output

# input data:
PISM_INDATANAME=${BOOTDIR}/pism_Antarctica_5km.nc
PISM_TEMPSERIES=${BOOTDIR}/pism_dT.nc
PISM_SLSERIES=${BOOTDIR}/pism_dSL.nc

###################################################################
NN=16  # default number of processors
if [ $# -gt 0 ] ; then  # if user says "antspinup.sh 8" then NN = 8
  NN="$1"
fi

echo "$SCRIPTNAME              NN = $NN"
set -e  # exit on error

###################################################################

if [ -n "${PISM_ON_CLUSTER:+1}" ]; then  # check if env var is set
  echo "$SCRIPTNAME this run was submitted, use MPI"
  PISM_MPIDO="mpiexec -machinefile ./log/hostlist -n"
  echo "$SCRIPTNAME      PISM_MPIDO = $PISM_MPIDO"
else
  echo "$SCRIPTNAME this is interactive, skip use of MPI"
  PISM_MPIDO=""
  NN=""
  echo "$SCRIPTNAME      PISM_MPIDO = $PISM_MPIDO"
fi

# check if env var PISM_DO was set (i.e. PISM_DO=echo for a 'dry' run) #I think I do not use this!!!
if [ -n "${PISM_DO:+1}" ] ; then  # check if env var DO is already set
  echo "$SCRIPTNAME         PISM_DO = $PISM_DO  (already set)"
else
  PISM_DO="" 
fi
DO=$PISM_DO
###################################################################

### RUNTIME options:

# grids
THIRTYKMGRID="-Mx 200 -My 200 -Lz 5000 -Lbz 2000 -Mz 41 -Mbz 16"
TWENTYKMGRID="-Mx 300 -My 300 -Lz 5000 -Lbz 2000 -Mz 41 -Mbz 16"
FIFTEENKMGRID="-Mx 400 -My 400 -Lz 5000 -Lbz 2000 -Mz 81 -Mbz 21"
TWELVEKMGRID="-Mx 500 -My 500 -Lz 5000 -Lbz 2000 -Mz 101 -Mbz 31"
TENKMGRID="-Mx 600 -My 600 -Lz 5000 -Lbz 2000 -Mz 101 -Mbz 31"
SEVENKMGRID="-Mx 900 -My 900 -Lz 5000 -Lbz 2000 -Mz 151 -Mbz 31"
FIVEKMGRID="-Mx 1200 -My 1200 -Lz 5000 -Lbz 2000 -Mz 201 -Mbz 51"

# skips:  
SKIPTHIRTYKM=50
SKIPTWENTYKM=50
SKIPFIFTEENKM=50
SKIPTWELVEKM=50
SKIPTENKM=100
SKIPSEVENKM=100
SKIPFIVEKM=200

SIA_ENHANCEMENT="-e 5.6"

#PIK-stuff:
#INFO: in pism, the option '-pik' is implemented, and activates '-cfbc -part_grid -part_redist -kill_icebergs'
#INFO: -meltfactor_pik 5e-3 is default when using -ocean pik
PIKPHYS="-ssa_method fd -e_ssa 0.6 -pik -eigen_calving 2.0e18 -calving_at_thickness 50.0"
PIKPHYS_COUPLING="-atmosphere pik -ocean pik -meltfactor_pik 1.5e-2"

# sliding related options:
PARAMS="-pseudo_plastic_q 0.25 -plastic_pwfrac 0.97"
TILLPHI="-topg_to_phi 5.0,20.0,-300.0,700.0"
#TILLPHI="-topg_to_phi 5.0,20.0,-1000.0,0.0" # as in martin_winkelmann11
FULLPHYS="-ssa_sliding -thk_eff $PARAMS $TILLPHI"



echo "$SCRIPTNAME             PISM = $PISM_EXEC"
echo "$SCRIPTNAME         FULLPHYS = $FULLPHYS"
echo "$SCRIPTNAME          PIKPHYS = $PIKPHYS"
echo "$SCRIPTNAME PIKPHYS_COUPLING = $PIKPHYS_COUPLING"


###################################################################

### RUN


# #######################################
# bootstrap and SHORT smoothing run to 100 years
# #######################################
stage=smoothing
INNAME=$PISM_INDATANAME
RESNAME=${RESDIR}$stage.nc
OUTNAME=${OUTDIR}$stage.out
RUNTIME=100 
echo
echo "$SCRIPTNAME  bootstrapping plus short SIA run for $RUNTIME a"
cmd="$PISM_MPIDO $NN $PISM_EXEC -skip 10 -boot_file ${INNAME} $FIFTEENKMGRID \
	$SIA_ENHANCEMENT $PIKPHYS_COUPLING -ocean_kill \
	-y $RUNTIME \
	-o $RESNAME -o_size medium"
echo $DO $cmd
$DO $cmd >> $OUTNAME
#exit # <-- uncomment to stop here

# #######################################
# run with -no_mass (no surface change) on 15km for 200ka
# #######################################
stage=nomass
INNAME=$RESNAME
RESNAME=${RESDIR}$stage.nc
OUTNAME=${OUTDIR}$stage.out
TSNAME=${RESDIR}ts_$stage.nc
RUNTIME=200000 
EXTRANAME=${RESDIR}extra_$stage.nc
exfilepackage="-extra_times 0:10000:$RUNTIME -extra_vars bmelt,bwat,csurf,temppabase,diffusivity,hardav"

echo
echo "$SCRIPTNAME  -no_mass (no surface change) SIA for $RUNTIME a"
cmd="$PISM_MPIDO $NN $PISM_EXEC -verbose 3 -i $INNAME $PIKPHYS_COUPLING  \
	$SIA_ENHANCEMENT -no_mass \
  	-y $RUNTIME \
	-extra_file $EXTRANAME $exfilepackage \
  	-o $RESNAME"
echo $DO $cmd
$DO $cmd >> $OUTNAME
#exit # <-- uncomment to stop here

# #######################################
# run into steady state with constant climate forcing
# #######################################
stage=run
#INNAME=${BOOTDIR}/nomass.nc
INNAME=$RESNAME
RESNAME=${RESDIR}$stage.nc
OUTNAME=${OUTDIR}$stage.out
TSNAME=${RESDIR}ts_$stage.nc
RUNTIME=100000 
EXTRANAME=${RESDIR}extra_$stage.nc
exfilepackage="-extra_times 0:1000:$RUNTIME -extra_vars thk,usurf,cbase,cbar,mask,diffusivity,tauc,bmelt,bwat,temp "

echo
echo "$SCRIPTNAME  run into steady state with constant climate forcing for $RUNTIME a"
cmd="$PISM_MPIDO $NN $PISM_EXEC -skip 10 -i $INNAME \
	$SIA_ENHANCEMENT $PIKPHYS_COUPLING $PIKPHYS $FULLPHYS \
	-ys 0 -y $RUNTIME \
	-ts_file $TSNAME -ts_times 0:1:$RUNTIME \
	-extra_file $EXTRANAME $exfilepackage \
	-o $RESNAME -o_size big"
	
echo $DO $cmd 
$DO $cmd >> $OUTNAME
#exit # <-- uncomment to stop here

# #######################################
## do a regridding to 10km:
# #######################################
#NN=64
#stage=run_regrid10km
#INNAME=${RESDIR}run.nc
#RESNAME=${RESDIR}$stage.nc
#OUTNAME=${OUTDIR}$stage.out
#TSNAME=${RESDIR}ts_$stage.nc
#RUNTIME=10000
#EXTRANAME=${RESDIR}extra_$stage.nc
#exfilepackage="-extra_times 0:500:$RUNTIME -extra_vars thk,usurf,cbase,cbar,mask,diffusivity,bmelt,bwat "

#echo
#echo "$SCRIPTNAME  run into steady state with constant climate forcing.. regridding to 10km"
#cmd="$PISM_MPIDO $NN $PISM_EXEC -skip $SKIPTENKM -regrid_file $INNAME -regrid_vars litho_temp,thk,enthalpy,bwat\
#	-boot_file $PISM_INDATANAME $TENKMGRID \
#	$SIA_ENHANCEMENT $PIKPHYS_COUPLING $PIKPHYS $FULLPHYS \
#	-ys 0 -y $RUNTIME \
#	-ts_file $TSNAME -ts_times 0:1:$RUNTIME \
#	-extra_file $EXTRANAME $exfilepackage \
#	-o $RESNAME -o_size big"
#	
#echo $DO $cmd 
#$DO $cmd >> $OUTNAME
##exit # <-- uncomment to stop here

# #######################################
## do a regridding to 6.7km:
# #######################################
#NN=128
#stage=run_regrid7km
#INNAME=${RESDIR}run.nc
#RESNAME=${RESDIR}$stage.nc
#OUTNAME=${OUTDIR}$stage.out
#TSNAME=${RESDIR}ts_$stage.nc
#RUNTIME=5000
#EXTRANAME=${RESDIR}extra_$stage.nc
#exfilepackage="-extra_times 0:500:$RUNTIME -extra_vars thk,usurf,cbase,cbar,mask,diffusivity,bmelt,bwat "

#echo
#echo "$SCRIPTNAME  run into steady state with constant climate forcing.. regridding to 6.7km"
#cmd="$PISM_MPIDO $NN $PISM_EXEC -skip $SKIPSEVENKM -regrid_file $INNAME -regrid_vars litho_temp,thk,enthalpy,bwat\
#	-boot_file $PISM_INDATANAME $SEVENKMGRID \
#	$SIA_ENHANCEMENT $PIKPHYS_COUPLING $PIKPHYS $FULLPHYS \
#	-ys 0 -y $RUNTIME \
#	-ts_file $TSNAME -ts_times 0:1:$RUNTIME \
#	-extra_file $EXTRANAME $exfilepackage \
#	-o $RESNAME -o_size big"
#	
#echo $DO $cmd 
#$DO $cmd >> $OUTNAME
##exit # <-- uncomment to stop here

# #######################################
## do a regridding to 5km:
# #######################################
#NN=128
#stage=run_regrid_5km
#INNAME=${RESDIR}run.nc
#RESNAME=${RESDIR}$stage.nc
#OUTNAME=${OUTDIR}$stage.out
#TSNAME=${RESDIR}ts_$stage.nc
#RUNTIME=1000
#EXTRANAME=${RESDIR}extra_$stage.nc
#exfilepackage="-extra_times 0:250:$RUNTIME -extra_vars thk,usurf,cbase,cbar,mask,diffusivity,bmelt,bwat "

#echo
#echo "$SCRIPTNAME  run into steady state with constant climate forcing"
#cmd="$PISM_MPIDO $NN $PISM_EXEC -skip $SKIPFIVEKM -regrid_file $INNAME -regrid_vars litho_temp,thk,enthalpy,bwat\
#	-boot_file $PISM_INDATANAME $FIVEKMGRID \
#	$SIA_ENHANCEMENT $PIKPHYS_COUPLING $PIKPHYS $FULLPHYS \
#	-ys 0 -y $RUNTIME \
#	-ts_file $TSNAME -ts_times 0:1:$RUNTIME \
#	-extra_file $EXTRANAME $exfilepackage \
#	-o $RESNAME -o_size big"
#	
#echo $DO $cmd 
#$DO $cmd >> $OUTNAME
##exit # <-- uncomment to stop here


echo
echo "$SCRIPTNAME  spinup done"





