#!/bin/sh

# VERIFYFULL is a script to do the *full* verification of the isothermal and 
# thermocoupled shallow ice components of ice model COMMVNISM.
# Takes about [A LONG TIME!]
# ELB 5/12/06

echo " "
echo "VERIFYFULL:  THIS WILL TAKE A LONG TIME!"
echo "using -adapt_ratio 0.12  throughout"

echo " "
#echo "++++++++ starting with isothermal test B and Mx=31,61,121,241 and Mz=31:"
echo "++++++++ starting with isothermal test B and Mx=31,61,91 and Mz=31:"
#for myMx in 31 61 121 241
for myMx in 31 61 91
do
   ./verify -test B -Mx $myMx -My $myMx -Mz 31 -adapt_ratio 0.12 -ys 422.45 -y 25000.0 > _temp_result.txt 
   sed '/  history =/,+1!d' _temp_result.txt | sed 1d
   sed '/  prcntVOL/,+1!d' _temp_result.txt
   date
done

echo " "
#echo "++++++++ next: isothermal test C and Mx=31,61,121,241 and Mz=31:"
echo "++++++++ next: isothermal test C and Mx=31,61,91 and Mz=31:"
#for myMx in 31 61 121 241
for myMx in 31 61 91
do
   ./verify -test C -Mx $myMx -My $myMx -Mz 31 -adapt_ratio 0.12 -y 15208.0 > _temp_result.txt 
   sed '/  history =/,+1!d' _temp_result.txt | sed 1d
   sed '/  prcntVOL/,+1!d' _temp_result.txt
   date
done

echo " "
#echo "++++++++ next: isothermal test D and Mx=31,61,121,241 and Mz=31:"
echo "++++++++ next: isothermal test D and Mx=31,61,91 and Mz=31:"
#for myMx in 31 61 121 241
for myMx in 31 61 91
do
   ./verify -test D -Mx $myMx -My $myMx -Mz 31 -adapt_ratio 0.12 -y 25000 > _temp_result.txt 
   sed '/  history =/,+1!d' _temp_result.txt | sed 1d
   sed '/  prcntVOL/,+1!d' _temp_result.txt
   date
done

echo " "
echo "using -maxdt 10.0 and -tempskip 10 for remaining thermocoupled tests"

echo " "
#echo "+++++++++ next: thermocoupled test F and Mx=61,91,121,181,241 and Mz=61:"
echo "+++++++++ next: thermocoupled test F and Mx=61,91,121 and Mz=61:"
#for myMx in 61 91 121 181 241
for myMx in 61 91 121
do
   ./verify -test F -Mx $myMx -My $myMx -Mz 61 -y 200000.0 -adapt_ratio 0.12 -maxdt 10.0 -tempskip 10 > _temp_result.txt 
   sed '/  history =/,+1!d' _temp_result.txt | sed 1d
   sed '/  prcntVOL/,+1!d' _temp_result.txt
   date
done

echo " "
#echo "+++++++++ next: thermocoupled test G and Mx=61,91,121,181,241 and Mz=61:"
echo "+++++++++ next: thermocoupled test G and Mx=61,91,121 and Mz=61:"
#for myMx in 61 91 121 181 241
for myMx in 61 91 121
do
   ./verify -test G -Mx $myMx -My $myMx -Mz 61 -y 200000.0 -adapt_ratio 0.12 -maxdt 10.0 -tempskip 10 > _temp_result.txt 
   sed '/  history =/,+1!d' _temp_result.txt | sed 1d
   sed '/  prcntVOL/,+1!d' _temp_result.txt
   date
done

echo " "
echo "VERIFYFULL done!"
