/* This Maxima script derives H[0] and H[1], ice thicknesses at two
adjacent grid points needed to achieve the "LI" grounding line
position parameterization lambda defined below.

z[0] is the sea level elevation, mu = rho_ice / rho_ocean

I assume that the bed is flat and that the bed elevation is zero.
*/

/* Assume that H[1] is half of H[0] */
H[1] : H[0] / 2;

/* definitions of alpha and beta */
alpha : mu * H[0] - z[0];
beta  : mu * H[1] - z[0];

/* lambda, as derived from the linear approximation of ice thickness. */
lambda : alpha / (alpha - beta);

/* Redefine lambda_target and re-run to recompute H[0]. */
lambda_target : 0.5;

solve(lambda = lambda_target, H[0]);
