language: cpp

dist: bionic

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - cmake
      - cdo
      - nco
      - ncview
      - mpich
      - libmpich-dev
      - libfftw3-dev
      - libgsl-dev
      - libproj-dev
      - libudunits2-dev
      - libx11-dev
      - libblas-dev
      - liblapack-dev
      - libnetcdf-dev
      - libopenmpi-dev
      - netcdf-bin
      - openmpi
      - python-dev
      - python-pyproj
      - python-netcdf4
      - petsc-dev

install:
  - "mkdir -p build && cd build && 
  CC=mpicc CXX=mpicxx =
  PETSC_DIR=/usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real/ \
  PISM_INSTALL_PREFIX=~/pism cmake .. && make"

script:
  - cd build && make test

notifications:
  email: false
