#!/bin/bash

# Copyright (C) 2010 Ed Bueler

# see README for role of this script

# This script uses NCO (http://nco.sourceforge.net/).

SCRIPTNAME="#(runcase.sh)"

set -e  # exit on error

DIFFSFILE=$5  # file which this script MODIFIES by appending a line of
              #   results; if runcase.sh has no 5th argument, then, because
              #   of how objective.py works, the results will appear at stdout

DATANAME=Greenland_5km_v1.1.nc
PISMDATA=pism_$DATANAME        # name of PISM file with Greenland geometry and
                               #   smb from Ettema et al.
                               #   and other needed info to run pclimate

BASECONFIG=base_config.nc      # name of -config_override, for modification

STARTFILE=start.nc             # name of file generated by pismr; see boot.sh


#   use arguments of script to set params:
THRESHOLD=$1
DDFSNOW=$2
REFREEZE=$3
STDDEV=$4

DDFICE=`echo "2.0*$DDFSNOW" |bc`  # multiply by two to get DDF for ice

NAMEROOT=${THRESHOLD}_${DDFSNOW}_${REFREEZE}_${STDDEV}

echo "$SCRIPTNAME  CASE = ${NAMEROOT}"

CONFIG=config_${NAMEROOT}.nc
echo "$SCRIPTNAME  creating -config_override file $CONFIG ..."
rm -rf $CONFIG
ncks -O $BASECONFIG $CONFIG      
ncatted -O -a pdd_positive_threshold_temp,pism_overrides,m,d,$THRESHOLD $CONFIG
ncatted -O -a pdd_factor_snow,pism_overrides,m,d,$DDFSNOW $CONFIG
ncatted -O -a pdd_factor_ice,pism_overrides,m,d,$DDFICE $CONFIG
ncatted -O -a pdd_refreeze,pism_overrides,m,d,$REFREEZE $CONFIG
ncatted -O -a pdd_std_dev,pism_overrides,m,d,$STDDEV $CONFIG

CLIMATE=clim_${NAMEROOT}.nc    # name of output of pclimate, which will be
                               #   evaluated against $PISMDATA

# change this to "mpiexec -n 8" or similar to run on multiple processes
MPIDO=""
# coupler settings: Fausto 2m air temp parameterization, but default PDD
#   (w/o Greve/Fausto settings of PDD parameters)
COUPLER="-atmosphere searise_greenland -surface pdd"
CLIMSTARTTIME=1990
CLIMENDTIME=1991
#DT=0.0833333333 # monthly = (1/12) of year
DT=1.0
echo
echo "$SCRIPTNAME  running pclimate with -config_override file $CONFIG to generate"
echo "$SCRIPTNAME    $CLIMATE containing ice surface mass balance 'acab'"

$MPIDO pclimate -i $STARTFILE $COUPLER -config_override $CONFIG \
  -ys $CLIMSTARTTIME -ye $CLIMENDTIME -dt $DT -o $CLIMATE

echo "  computing objective functions by comparing 'acab' in $CLIMATE"
echo "    to 'smb' in $PISMDATA and putting objective value in $DIFFSFILE"
./objective.py -v acab,smb -H $STARTFILE $CLIMATE $PISMDATA $DIFFSFILE
echo

if [ -n "${DELETECLIMATE:+1}" ] ; then
  echo "$SCRIPTNAME  env var DELETECLIMATE set so deleting $CONFIG and $CLIMATE ..."
  rm -rf $CONFIG  # don't need this file any more BECAUSE pism_overrides are
                  #   carried forward into $OUTFILE
  rm -rf $CLIMATE
fi

echo

