# -*- coding: utf-8 -*-
#
# PISM, a Parallel Ice Sheet Model documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.

# -- General configuration ------------------------------------------------

import os
import sys
import re

src_directory="${CMAKE_CURRENT_SOURCE_DIR}"

# Add the src_directory to the Python path to help Sphinx find the pism_config extension.
sys.path.append(src_directory)

# If your documentation needs a minimal Sphinx version, state it here.
#
needs_sphinx = '3.0'

nitpicky = True

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.mathjax',
              'sphinx.ext.githubpages',
              'sphinxcontrib.bibtex',
              'pism_config']
bibtex_bibfiles=[os.path.join(src_directory, "../ice-bib.bib")]

# Add any paths that contain templates here, relative to this directory.
templates_path = [os.path.join(src_directory, '_templates')]

# The suffix(es) of source filenames.
source_suffix = '.rst'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also affect html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# This is needed to be able to put .. bibliography:: in a "References" section in HTML and
# just in the main document in LaTeX. (Otherwise Sphinx produces an empty "References"
# section in LaTeX.)

if tags.has('latex'):
    master_doc = 'index_latex'
    exclude_patterns.append('index.rst')
    exclude_patterns.append('zzz_references_html.rst')
else:
    master_doc = 'index'
    exclude_patterns.append('index_latex.rst')
    exclude_patterns.append('zzz_references_latex.rst')

# General information about the project.
project = 'PISM, a Parallel Ice Sheet Model'
copyright = '2004--2023, the PISM authors'
author = 'the PISM authors'

# The version info for the project you're documenting, acts as replacement for |version|
# and |release|, also used in various other places throughout the built documents.
#
# The short X.Y.Z version.
version="${Pism_VERSION}"
# The full version, including commit hash, date, and commit author (if available)
release="${Pism_VERSION_LONG}"

# Path to PISM's configuration file
pism_config_file="${CMAKE_CURRENT_BINARY_DIR}/pism_config.nc"

# The language for content autogenerated by Sphinx.
language = 'en'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# numbered figures and tables
numfig = True

# -- Options for HTML output ----------------------------------------------

html_theme = 'alabaster'

html_show_sourcelink = False

html_theme_options = {"logo": "pism-logo.png",
                      "github_button": False,
                      "show_powered_by": False,
                      "body_text_align": "justify",
                      #                      "sidebar_collapse" : True,
                      }

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [os.path.join(src_directory, '_static'),
                    os.path.join(src_directory, 'logo')]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'searchbox.html',
    ]
}

# -- Options for LaTeX output ----------------

latex_documents = [
    (master_doc, 'pism_manual.tex', project, author, 'manual'),
]

# latex_show_pagerefs = True

latex_elements = {
    'releasename': "version",
    'preamble': r'''
     \usepackage{txfonts}
     % work-around for a bug in sphinxcontrib-bibtex (https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/276)
     \usepackage{etoolbox}
     \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}
'''
}

# -- Add custom math definitions ----------------

mathjax3_config = {"tex": {"macros": {}}}

# Add math definitions to the LaTeX preamble and MathJax settings:
for line in open(os.path.join(src_directory, "math-definitions.tex")):
    M = re.match(r"\\newcommand{\\([a-zA-Z]+)}(\[([0-9]+)\])?(\[(.+)\])?{(.+)}", line)

    if M:
        name = M.group(1)
        definition = M.group(6)
        if M.group(2):
            args = M.group(3)
            if M.group(4):
                default = M.group(5)
                mathjax3_config["tex"]["macros"][name] = [definition, args, default]
            else:
                mathjax3_config["tex"]["macros"][name] = [definition, args]
        else:
            mathjax3_config["tex"]["macros"][name] = definition
        latex_elements["preamble"] += line

# Support Sphinx 3.x:
import sphinx
if sphinx.version_info[0] < 4:
    mathjax_config = {"TeX" : {"Macros" : {}}}
    mathjax_config["TeX"]["Macros"] = mathjax3_config["tex"]["macros"]
