FROM debian:buster
RUN apt-get update
RUN apt-get install -y git cmake g++ netcdf-bin libgsl-dev libnetcdf-dev libfftw3-dev libudunits2-dev petsc-dev

RUN useradd -m --shell=/bin/nologin builder && usermod -L builder
USER builder

RUN mkdir -p /home/builder/local/build/pism
WORKDIR /home/builder/local
RUN git clone --depth=1 git://github.com/pism/pism.git

WORKDIR build/pism
ENV PISM_INSTALL_PREFIX=/home/builder/
ENV CC=mpicc CXX=mpicxx
RUN cmake ../../pism
RUN make install

# Set PYTHONPATH so that "import PISM" succeeds.
ENV PYTHONPATH=$PISM_INSTALL_PREFIX/lib/python2.7/site-packages:$PYTHONPATH

# Add a flag needed to use OpenMPI in a Docker container.
# See https://github.com/open-mpi/ompi/issues/4948
# Tested with OpenMPI version 3.1.3 on Debian 10 (buster)
ENV OMPI_MCA_btl="^vader"

# Allow oversubscribing (i.e. running more MPI processes than the number of cores
# available). Run "ompi_info --all" to get the list of MCA parameters.
ENV OMPI_MCA_rmaps_base_oversubscribe=yes
