FROM debian:buster
RUN apt-get update && apt-get install -y wget ${PISM_DEBIAN_PACKAGE_LIST}

RUN useradd --create-home --system --shell=/bin/false builder && usermod --lock builder
USER builder

# Install parallel HDF5 and NetCDF by building them from sources.
#
# Uses wget installed above.
COPY build_netcdf.sh /tmp/
RUN /tmp/build_netcdf.sh

# Add a flag needed to use OpenMPI in a Docker container.
# See https://github.com/open-mpi/ompi/issues/4948
# Tested with OpenMPI version 3.1.3 on Debian 10 (buster)
#
# Allow oversubscribing (i.e. running more MPI processes than the number of cores
# available). Run "ompi_info --all" to get the list of MCA parameters.
ENV OMPI_MCA_btl="^vader" \
    OMPI_MCA_rmaps_base_oversubscribe=yes
