FROM debian:buster
RUN apt-get update
RUN apt-get install -y git cmake g++ netcdf-bin libgsl-dev libnetcdf-dev libfftw3-dev libudunits2-dev petsc-dev

RUN useradd -m --shell=/bin/nologin builder && usermod -L builder
USER builder

RUN mkdir -p /home/builder/local/build/pism
WORKDIR /home/builder/local
RUN git clone --depth=1 git://github.com/pism/pism.git

WORKDIR build/pism
ENV PISM_INSTALL_PREFIX=/home/builder/
ENV CC=mpicc CXX=mpicxx
RUN cmake ../../pism
RUN make install
