FROM archlinux/base:latest
RUN pacman -Sy
RUN pacman --noconfirm -S git base-devel

RUN useradd -m --shell=/bin/nologin build && usermod -L build
RUN echo "build ALL = NOPASSWD: /usr/bin/pacman" >> /etc/sudoers
USER build
WORKDIR /home/build/
RUN git clone https://aur.archlinux.org/yay.git
WORKDIR yay
RUN makepkg --noconfirm -si
RUN yay --noconfirm --answerdiff=None -Sy pism
