FROM archlinux/base:latest
RUN groupadd -r runner -g 1000 && useradd -u 1000 -r -g runner -m -d /runner -s /sbin/nologin -c 'CI' runner && chmod 755 /runner
RUN yes | pacman -Sqy git binutils sudo go
WORKDIR /runner/build
RUN git clone https://aur.archlinux.org/yay.git
WORKDIR /runner/build/yay
USER runner:runner
RUN makepkg -si
USER root:root
RUN yay -Sy pism
