#!/usr/bin/env python3

# @package nc2cdo
# \author Andy Aschwanden, University of Alaska Fairbanks, USA
# \brief Script makes netCDF file ready for Climate Data Operators (CDO).
# \details Script adds attributes and variables to a netCDF which are required for
# post-processing with <a href="http://www.mad.zmaw.de/Pingo/post/post.cdo.home.html">CDO</a>.
# That is, the attribute 'coordinates = "lon lat"' is added to any gridded variable
# found in the file, except for lat and lon. For remapping methods other than bilinear,
# CDO additionally needs the corners of each grid cell (the lat/lon variables define the
# cell centers). We compute the corners of each grid cell on the x-y grid because this is
# relatively straightforward (compared to the lat-lon world), and then project the corners
# onto the lat-lon grid. The script attemps to retrieve the required mapping information from,
# if present, a global attribute called 'projection' which (hopefully) contains a valid
# Proj projection string. If this string is not available (this is true for standard PISM
# output), the script searches variables for the 'grid_mapping' attribute and translates information
# from the corresponding mapping variable into a Proj projection string. If neither is found,
# the script exits with an error message.
#
# Usage:
#
# \verbatim $ nc2cdo.py foo.nc \endverbatim

import os
import sys
import numpy as np
from argparse import ArgumentParser

from pyproj import Proj

try:
    import xarray as xr
except ImportError:
    print("xarray is not installed!")
    sys.exit(1)

# Set up the option parser
parser = ArgumentParser()
parser.description = """Script makes netCDF file ready for Climate Data Operators (CDO). Either a global attribute "projection", a mapping variable, or a command-line proj string or a EPSG code must be given."""
parser.add_argument("FILE", nargs=1)
parser.add_argument(
    "--no_bounds", dest="bounds", action="store_false", help="do not add lat/lon bounds.", default=True
)
parser.add_argument(
    "--srs",
    dest="srs",
    help="""
                  a valid proj string describing describing the projection
                  """,
    default=None,
)
options = parser.parse_args()
args = options.FILE
srs = options.srs
bounds = options.bounds

if len(args) == 1:
    nc_outfile = args[0]
else:
    print("wrong number arguments, 1 expected")
    parser.print_help()
    exit(0)

# Get projection information from an xarray Dataset


def get_projection_from_file(ds):

    # First, check global attributes 'proj' / 'projection' which contain a Proj string.
    for attr in ("proj", "projection"):
        if attr in ds.attrs:
            try:
                p = Proj(str(ds.attrs[attr]))
                print("Found projection information in global attribute %s, using it" % attr)
                return p
            except Exception:
                pass

    # Otherwise look for a variable carrying a 'grid_mapping' attribute.
    mappingvarname = None
    for name in ds.variables:
        if "grid_mapping" in ds[name].attrs:
            mappingvarname = ds[name].attrs["grid_mapping"]
            print('Found projection information in variable "%s", using it' % mappingvarname)
            break

    if mappingvarname is None or mappingvarname not in ds.variables:
        print("No mapping information found, exiting.")
        sys.exit(1)

    m = ds[mappingvarname].attrs
    try:
        p = Proj(
            proj="stere",
            ellps=m["ellipsoid"],
            datum=m["ellipsoid"],
            units="m",
            lat_ts=m["standard_parallel"],
            lat_0=m["latitude_of_projection_origin"],
            lon_0=m["straight_vertical_longitude_from_pole"],
            x_0=m["false_easting"],
            y_0=m["false_northing"],
        )
    except KeyError as e:
        print("Mapping variable %s is missing required attribute %s; exiting."
              % (mappingvarname, e))
        sys.exit(1)

    return p


if __name__ == "__main__":

    # Load the dataset into memory and detach the file handle so we can
    # rewrite the same path safely below.
    ds = xr.open_dataset(nc_outfile, decode_times=False, decode_cf=False).load()
    ds.close()

    # a list of possible x-dimensions names
    xdims = ["x", "x1"]
    # a list of possible y-dimensions names
    ydims = ["y", "y1"]

    xdim = next((d for d in xdims if d in ds.dims), None)
    ydim = next((d for d in ydims if d in ds.dims), None)
    if xdim is None or ydim is None:
        print("Could not find an x-dimension or y-dimension in %s." % nc_outfile)
        sys.exit(1)

    # values of the coordinate variable in x-direction
    easting = np.asarray(ds[xdim].values)
    # values of the coordinate variable in y-direction
    northing = np.asarray(ds[ydim].values)

    # grid spacing in x-direction
    de = np.diff(easting)[0]
    # grid spacing in y-direction
    dn = np.diff(northing)[0]

    # number of grid points in x-direction
    M = easting.shape[0]
    # number of grid points in y-direction
    N = northing.shape[0]

    # number of grid corners
    grid_corners = 4
    # grid corner dimension name
    grid_corner_dim_name = "nv4"

    # array holding x-component of grid corners
    gc_easting = np.zeros((M, grid_corners))
    # array holding y-component of grid corners
    gc_northing = np.zeros((N, grid_corners))
    # array holding the offsets from the cell centers
    # in x-direction (counter-clockwise)
    de_vec = np.array([-de / 2, de / 2, de / 2, -de / 2])
    # array holding the offsets from the cell centers
    # in y-direction (counter-clockwise)
    dn_vec = np.array([-dn / 2, -dn / 2, dn / 2, dn / 2])
    # array holding lat-component of grid corners
    gc_lat = np.zeros((N, M, grid_corners))
    # array holding lon-component of grid corners
    gc_lon = np.zeros((N, M, grid_corners))

    if srs:
        # use projection from command line
        try:
            proj = Proj(srs)
        except Exception:
            proj = Proj(init=srs)
    else:
        # Get projection from file
        proj = get_projection_from_file(ds)

    if bounds:
        for corner in range(0, grid_corners):
            ## grid_corners in x-direction
            gc_easting[:, corner] = easting + de_vec[corner]
            # grid corners in y-direction
            gc_northing[:, corner] = northing + dn_vec[corner]
            # meshgrid of grid corners in x-y space
            gc_ee, gc_nn = np.meshgrid(gc_easting[:, corner], gc_northing[:, corner])
            # project grid corners from x-y to lat-lon space
            gc_lon[:, :, corner], gc_lat[:, :, corner] = proj(gc_ee, gc_nn, inverse=True)

    if bounds:
        ds["lon_bnds"] = xr.DataArray(
            gc_lon.astype("f4"),
            dims=(ydim, xdim, grid_corner_dim_name),
            attrs={"units": "degreesE"},
        )
        ds["lat_bnds"] = xr.DataArray(
            gc_lat.astype("f4"),
            dims=(ydim, xdim, grid_corner_dim_name),
            attrs={"units": "degreesN"},
        )

    ee, nn = np.meshgrid(easting, northing)
    lon, lat = proj(ee, nn, inverse=True)

    lon_attrs = {"units": "degreesE", "long_name": "Longitude",
                 "standard_name": "longitude"}
    lat_attrs = {"units": "degreesN", "long_name": "Latitude",
                 "standard_name": "latitude"}
    if bounds:
        lon_attrs["bounds"] = "lon_bnds"
        lat_attrs["bounds"] = "lat_bnds"

    ds["lon"] = xr.DataArray(lon.astype("f4"), dims=(ydim, xdim), attrs=lon_attrs)
    ds["lat"] = xr.DataArray(lat.astype("f4"), dims=(ydim, xdim), attrs=lat_attrs)

    # Make sure variables have 'coordinates' attribute
    skip = {"lat", "lon", "lat_bnds", "lon_bnds"}
    for name in ds.data_vars:
        if name in skip:
            continue
        if ds[name].ndim >= 2:
            ds[name].attrs["coordinates"] = "lon lat"

    # lat/lon coordinates must not have mapping and coordinate attributes
    for name in ("lat", "lon", "lat_bnds", "lon_bnds"):
        if name in ds.variables:
            ds[name].attrs.pop("grid_mapping", None)
            ds[name].attrs.pop("coordinates", None)

    # If present prepend history history attribute, otherwise create it
    from time import asctime

    histstr = asctime() + " : grid info for CDO added by nc2cdo.py, a PISM utility\n"
    if "History" in ds.attrs:
        ds.attrs["History"] = histstr + ds.attrs["History"]
    elif "history" in ds.attrs:
        ds.attrs["history"] = histstr + ds.attrs["history"]
    else:
        ds.attrs["history"] = histstr

    for attr in ("projection", "proj"):
        ds.attrs.pop(attr, None)
    # Write projection attribute
    ds.attrs["proj"] = proj.srs

    # Crash-safe in-place rewrite: write to a temp file then atomically replace.
    tmp = nc_outfile + ".tmp"
    ds.to_netcdf(tmp, mode="w")
    os.replace(tmp, nc_outfile)
