#!/usr/bin/env python3

# @package create_timeline
# \author Andy Aschwanden, University of Alaska Fairbanks, USA
# \brief Script creates a timeline for enviornmental forcing.
# \details Script creates a timeline file that can be used with
# the -time_file option and -*_given_file to control the applicaton
# of forcing data, and to control start and end date of a PISM simulation.
#
# Say you have monthly climate forcing from 1980-1-1 through 2001-1-1 in
# the forcing file foo_1980-1999.nc to be used with, e.g. -surface_given_file,
# but you want the model to run from 1991-1-1 through 2001-1-1.
#
# Usage:
#
# \verbatim $ create_timeline.py --start_date '1991-1-1' -end_date '2001-1-1'
# time_1991-2000.nc \endverbatim

import os
import sys
from argparse import ArgumentParser
from dateutil import rrule
from dateutil.parser import parse
from datetime import datetime
import time
import numpy as np

try:
    import xarray as xr
except ImportError:
    print("xarray is not installed!")
    sys.exit(1)
import cftime

# Set up the option parser
parser = ArgumentParser()
parser.description = """Script creates a time file with time and time
bounds that can be used to determine to force PISM via command line
option -time_file"""
parser.add_argument("FILE", nargs="*")
parser.add_argument(
    "-c",
    "--calendar",
    dest="calendar",
    choices=["standard", "gregorian", "no_leap", "365_day", "360_day", "julian"],
    help="""Sets the calendar. Default="standard".""",
    default="standard",
)
parser.add_argument(
    "-p",
    "--periodicity",
    dest="periodicity",
    help="""periodicity, e.g. monthly, daily, etc. Default=monthly""",
    default="monthly",
)
parser.add_argument(
    "-a", "--start_date", dest="start_date", help="""Start date in ISO format. Default=1989-1-1""", default="1989-1-1"
)
parser.add_argument(
    "-e", "--end_date", dest="end_date", help="""End date in ISO format. Default=2012-1-1""", default="2012-1-1"
)
parser.add_argument(
    "-i",
    "--interval_type",
    dest="interval_type",
    choices=["start", "mid", "end"],
    help="""Defines whether the time values t_k are the end points of the time bounds tb_k or the mid points 1/2*(tb_k -tb_(k-1)). Default="mid".""",
    default="mid",
)
parser.add_argument(
    "-u",
    "--ref_unit",
    dest="ref_unit",
    help="""Reference unit. Default=days. Use of months or
                    years is NOT recommended.""",
    default="days",
)
parser.add_argument(
    "-d", "--ref_date", dest="ref_date", help="""Reference date. Default=1960-1-1""", default="1960-1-1"
)

options = parser.parse_args()
interval_type = options.interval_type
periodicity = options.periodicity.upper()
start_date = parse(options.start_date)
end_date = parse(options.end_date)
ref_unit = options.ref_unit
ref_date = options.ref_date
args = options.FILE
infile = args[0]

time_units = "%s since %s" % (ref_unit, ref_date)
calendar = options.calendar

# create a dictionary so that we can supply the periodicity as a
# command-line argument.
pdict = {}
pdict["SECONDLY"] = rrule.SECONDLY
pdict["MINUTELY"] = rrule.MINUTELY
pdict["HOURLY"] = rrule.HOURLY
pdict["DAILY"] = rrule.DAILY
pdict["WEEKLY"] = rrule.WEEKLY
pdict["MONTHLY"] = rrule.MONTHLY
pdict["YEARLY"] = rrule.YEARLY
prule = pdict[periodicity]

# reference date from command-line argument
r = time_units.split(" ")[2].split("-")
refdate = datetime(int(r[0]), int(r[1]), int(r[2]))

# create list with dates from start_date until end_date with
# periodicity prule.
bnds_datelist = list(rrule.rrule(prule, dtstart=start_date, until=end_date))

# calculate the days since refdate, including refdate, with time being the
bnds_interval_since_refdate = cftime.date2num(bnds_datelist, time_units, calendar=calendar)
if interval_type == "mid":
    # mid-point value:
    # time[n] = (bnds[n] + bnds[n+1]) / 2
    time_interval_since_refdate = bnds_interval_since_refdate[0:-1] + np.diff(bnds_interval_since_refdate) / 2
elif interval_type == "start":
    time_interval_since_refdate = bnds_interval_since_refdate[:-1]
else:
    time_interval_since_refdate = bnds_interval_since_refdate[1:]

# variable names consistent with PISM
time_var_name = "time"
bnds_var_name = "time_bnds"
bnds_dim = "nb2"

time_attrs = {
    "bounds": bnds_var_name,
    "units": time_units,
    "calendar": calendar,
    "standard_name": time_var_name,
    "axis": "T",
}

# Build (or extend) the dataset.
if os.path.isfile(infile):
    ds = xr.open_dataset(infile, decode_times=False, decode_cf=False).load()
    ds.close()
else:
    ds = xr.Dataset()

ds = ds.assign_coords(
    {time_var_name: (time_var_name,
                     np.asarray(time_interval_since_refdate, dtype="f8"),
                     time_attrs)}
)

bnds = np.column_stack([bnds_interval_since_refdate[:-1],
                        bnds_interval_since_refdate[1:]]).astype("f8")
ds[bnds_var_name] = xr.DataArray(bnds, dims=(time_var_name, bnds_dim))

# writing global attributes
script_command = " ".join([time.ctime(), ":", os.path.basename(__file__),
                           " ".join([str(x) for x in args])])
ds.attrs["history"] = script_command
ds.attrs["Conventions"] = "CF 1.5"

# Write atomically (tmp + replace) to mirror the previous "open(a)/createVariable/close" flow.
tmp = infile + ".tmp" if os.path.isfile(infile) else infile
ds.to_netcdf(tmp, mode="w", unlimited_dims=[time_var_name],
             format="NETCDF3_CLASSIC")
if tmp != infile:
    os.replace(tmp, infile)
