#!/usr/bin/env python3
from sys import argv, exit
from getopt import getopt, GetoptError

# @package nccmp
# Compares NetCDF files by absolute max norms of difference of variables
##
# Without options,
# \code
# pism_nccmp foo.nc bar.nc
# \endcode
# compares all the variables in \c foo.nc and \c bar.nc.
##
# Option \c -v allows selecting varibles to compare:
# \code
# pism_nccmp -v thk,velbar_mag foo.nc bar.nc
# \endcode
# only compares \c thk and \c velbar_mag.
##
# Option \c -t sets the tolerance:
# \code
# pism_nccmp -t 1e-6 foo.nc bar.nc
# \endcode
# compares all the variables using the tolerance of 1e-6.
##
# Finally, option \c -x \b excludes variables given with \c -v, instead of
# selecting them for comparison.
##
# Run with --help to get a "usage" message.

tol = 0.0   # default tolerance is perfection


def success(relative):
    if relative:
        print("Files are the same within relative tolerance %.1e" % tol)
    else:
        print("Files are the same within tolerance %.1e" % tol)
    exit(0)


def failure():
    print("Files are different.")
    exit(1)


usage = """pism_nccmp compares NetCDF files by absolute max norms of difference of variables
usage:
  pism_nccmp foo.nc bar.nc            compare all variables
  pism_nccmp -v A,B foo.nc bar.nc     compare variables A and B
  pism_nccmp -x -v C foo.nc bar.nc    compare all variables except C
  pism_nccmp -t 1e-6 foo.nc bar.nc    use tolerance 1e-6 instead of default of 0"""


def usagefailure(message):
    print(message)
    print()
    print(usage)
    exit(2)


def compare_vars(ds1, ds2, name, tol, relative=False):
    import numpy as np

    if name not in ds1.variables:
        usagefailure("ERROR: VARIABLE '%s' NOT FOUND IN FILE 1" % name)
    if name not in ds2.variables:
        usagefailure("ERROR: VARIABLE '%s' NOT FOUND IN FILE 2" % name)

    a = np.squeeze(ds1[name].values)
    b = np.squeeze(ds2[name].values)

    if a.shape != b.shape:
        usagefailure("ERROR: VARIABLE '%s' OF INCOMPATIBLE SHAPES IN FILES" % name)

    # mask_and_scale (xarray default) turns _FillValue / missing_value into NaN.
    # Combine NaN locations from both arrays.
    if np.issubdtype(a.dtype, np.floating):
        mask = np.isnan(a) | np.isnan(b)
    else:
        mask = np.zeros(a.shape, dtype=bool)

    if mask.all():
        print('Variable %10s: no values to compare.' % name)
        return

    a = np.ma.array(a, mask=mask)
    b = np.ma.array(b, mask=mask)

    try:
        delta = abs(a - b).max()
    except TypeError:
        if (a == b).all():
            delta = 0
        else:
            delta = 1

    if relative:
        denom = max(abs(a).max(), abs(b).max())
        print("Variable %s: difference = %e, denominator = %e" % (name, delta, denom))
        if denom > 0:
            delta = delta / denom
            print("  Relative difference = %e" % (delta))

    # The actual check:
    #
    # Sometimes delta ends up being a denormalized number, which is zero
    # for all practical purposes, but is not zero, so we give up on
    # bit-for-bit equality here.
    if delta > tol:
        if tol == 0.0 and delta < 10 * np.finfo(float).tiny:
            print("Variable %s: Treating %e as zero." % (name, delta))
            return
        print("Variable %s: delta = %e, tol = %e" % (name, delta, tol))
        failure()


def compare(file1, file2, variables, exclude, tol, relative):
    try:
        import xarray as xr
    except ImportError:
        print("xarray is not installed!")
        exit(1)

    print("Comparing %s and %s" % (file1, file2))

    import numpy as np

    try:
        ds1 = xr.open_dataset(file1, decode_times=False, decode_cf=False)
    except Exception:
        usagefailure("ERROR: FILE '%s' CANNOT BE OPENED FOR READING" % file1)
    try:
        ds2 = xr.open_dataset(file2, decode_times=False, decode_cf=False)
    except Exception:
        usagefailure("ERROR: FILE '%s' CANNOT BE OPENED FOR READING" % file2)

    all_vars = np.unique(np.r_[list(ds1.variables), list(ds2.variables)])

    if not exclude:
        targets = variables if variables else all_vars
        for each in targets:
            compare_vars(ds1, ds2, each, tol, relative)
    else:
        for each in all_vars:
            if each in variables:
                continue
            compare_vars(ds1, ds2, each, tol, relative)


if __name__ == "__main__":
    from numpy import double
    try:
        opts, args = getopt(argv[1:], "t:v:xr", ["help", "usage"])
    except GetoptError:
        usagefailure('ERROR: INCORRECT COMMAND LINE ARGUMENTS FOR pism_nccmp')
    file1 = ""
    file2 = ""
    variables = []
    exclude = False
    relative = False
    for (opt, arg) in opts:
        if opt == "-t":
            tol = double(arg)
        if opt == "-x":
            exclude = True
        if opt == "-r":
            relative = True
        if opt == "-v":
            variables = arg.split(",")
        if opt in ("--help", "--usage"):
            print(usage)
            exit(0)

    if len(args) != 2:
        usagefailure('ERROR: WRONG NUMBER OF ARGUMENTS FOR pism_nccmp')

    compare(args[0], args[1], variables, exclude, tol, relative)

    success(relative)
