#!/usr/bin/env python3

# @package flowline
# \brief This script aids in setting up and visualizing flow-line modeling runs.
#
# \details This script expands and collapses NetCDF datasets along the 'x' or
# 'y' dimension. Run pism_flowline --help to see the command-line options.
#
# To set up a data-set for flow-line modeling, create a NetCDF file with an 'x'
# dimension and appropriate variables (usually x(x), acab(x), artm(x),
# bheatflx(x), thk(x) and topg(x)), then run
# \code
# pism_flowline -e -o foo_pism.nc foo.nc
# \endcode
# Then bootstrap from foo_pism.nc, adding -periodicity y to PISM command-line options.
#
# To collapse a PISM flow-line model output for plotting, etc, run
# \code
# pism_flowline -c -o bar.nc pism_output.nc
# \endcode

import sys
from optparse import OptionParser

try:
    import xarray as xr
except ImportError:
    print("xarray is not installed!")
    sys.exit(1)

import numpy as np

from sys import argv, exit
from time import asctime


def _strip_attrs(da):
    """Return a copy of attrs without _FillValue (it lives in encoding)."""
    a = dict(da.attrs)
    a.pop("_FillValue", None)
    return a


def _permute(da, output_order=("t", "z", "zb", "y", "x")):
    """Permute dimensions of a DataArray to match the output storage order."""
    dims = [d for d in output_order if d in da.dims]
    return da.transpose(*dims) if dims else da


def collapse_var(ds_in, ds_out, name, direction):
    """Save a collapsed (along ``direction``) copy of variable ``name``
    from ``ds_in`` into ``ds_out`` (the middle slice)."""
    da = ds_in[name]
    N = (ds_in.sizes[direction] - 1) // 2

    print("Processing %s..." % name)

    if len(da.dims) > 1 and direction in da.dims:
        sliced = da.isel({direction: N}, drop=True)
    else:
        sliced = da

    ds_out[name] = sliced


def expand_var(ds_in, ds_out, name, direction):
    """Save an expanded (along ``direction``) copy of variable ``name``
    from the 1D flowline ``ds_in`` into ``ds_out``."""
    if name == direction:
        return

    da = ds_in[name]
    print("Processing %s..." % name)

    # Coordinate variables: copy verbatim.
    if name in ("t", "z", "y", "x", "zb"):
        ds_out[name] = da
        return

    # Choose target dims based on the input rank, mirroring the original
    # heuristic in the netCDF4 implementation.
    if len(da.dims) == 1:
        target_dims = ("y", "x")
    elif len(da.dims) == 2:
        target_dims = ("t", "y", "x")
    elif len(da.dims) == 3:
        if name == "litho_temp":  # only variable depending on 'zb'
            target_dims = ("t", "zb", "y", "x")
        else:
            target_dims = ("t", "z", "y", "x")
    else:
        # Pass through unchanged.
        ds_out[name] = da
        return

    permuted = _permute(da).values
    pos = target_dims.index(direction)
    # Insert a singleton axis at the position of ``direction`` and broadcast
    # to size 3 along it. The other dims already follow output_order.
    new_shape = list(permuted.shape)
    new_shape.insert(pos, 1)
    target_shape = list(new_shape)
    target_shape[pos] = 3
    out = np.broadcast_to(permuted.reshape(new_shape), target_shape).copy()

    new = xr.DataArray(out, dims=target_dims, attrs=_strip_attrs(da), name=name)
    if "_FillValue" in da.encoding:
        new.encoding["_FillValue"] = da.encoding["_FillValue"]
    ds_out[name] = new


def process(input_path, output_path, direction, collapse):
    """Process the file ``input_path``, expanding or collapsing data
    according to ``collapse`` and ``direction``. Saves result in
    ``output_path``."""
    try:
        ds_in = xr.open_dataset(input_path, decode_times=False,
                                decode_cf=False).load()
        ds_in.close()
    except Exception:
        print("ERROR: Can't open %s" % input_path)
        exit(1)

    ds_out = xr.Dataset(attrs=dict(ds_in.attrs))

    if collapse:
        for name in list(ds_in.variables):
            if name == direction:
                continue
            collapse_var(ds_in, ds_out, name, direction)
    else:
        # Build the synthetic transverse coordinate variable: three points
        # at (-delta, 0, delta) using the original perpendicular spacing.
        perp = "y" if direction == "x" else "x"
        perp_var = ds_in[perp]
        delta = float(np.diff(np.asarray(perp_var.values))[0])
        dvals = np.array([-delta, 0.0, delta], dtype="f8")

        ds_out = ds_out.assign_coords({
            direction: (direction, dvals, {
                "axis": direction.upper(),
                "long_name": "%s-coordinate in Cartesian system" % direction.upper(),
                "standard_name": "projection_%s_coordinate" % direction,
                "units": perp_var.attrs.get("units", "m"),
            })
        })

        for name in list(ds_in.variables):
            expand_var(ds_in, ds_out, name, direction)

    message = asctime() + ': ' + ' '.join(argv) + '\n'
    if "history" in ds_out.attrs:
        ds_out.attrs["history"] = message + ds_out.attrs["history"]
    else:
        ds_out.attrs["history"] = message

    try:
        ds_out.to_netcdf(output_path, mode="w", format="NETCDF3_CLASSIC")
    except Exception as e:
        print("ERROR: Can't write %s: %s" % (output_path, e))
        exit(1)


parser = OptionParser()
parser.usage = "usage: %prog -o foo.nc -d {x,y} {--collapse,--expand} file.nc"
parser.description = "Collapses or expands a NetCDF file in a specified direction."

parser.add_option("-d", "--direction", dest="direction",
                  help="direction: one of x,y")
parser.add_option("-o", "--output", dest="output_filename",
                  help="output file")
parser.add_option("-e", "--expand", dest="expand", action="store_true",
                  help="expand")
parser.add_option("-c", "--collapse", dest="collapse", action="store_true",
                  help="collapse")

(opts, args) = parser.parse_args()

if len(args) != 1:
    print("ERROR: File argument is missing.")
    exit(1)


if (opts.expand and opts.collapse) or ((not opts.expand) and (not opts.collapse)):
    print("ERROR: exactly one of -e and -c is required.")
    exit(1)

if not opts.direction:
    if opts.collapse or (not opts.expand):
        opts.direction = 'y'
    else:
        try:
            with xr.open_dataset(args[0], decode_times=False,
                                 decode_cf=False) as probe:
                opts.direction = 'y' if 'x' in probe.variables else 'x'
        except Exception:
            opts.direction = 'x'
elif opts.direction not in ['x', 'y']:
    print("ERROR: Please specify direction using the -d option. (Choose one of x,y.)")
    exit(1)

if (not opts.output_filename):
    print("ERROR: Please specify the output file name using the -o option.")
    exit(1)

if opts.collapse:
    print("Collapsing %s in the %s direction, writing to %s..." % (args[0], opts.direction, opts.output_filename))
else:
    print("Expanding %s in the %s direction, writing to %s..." % (args[0], opts.direction, opts.output_filename))

process(args[0], opts.output_filename, opts.direction, opts.collapse or (not opts.expand))
