#!/usr/bin/env python3

# @package fill_missing
# @brief This script solves the Laplace equation as a method of filling holes in map-plane data.
#
# Uses an approximation to Laplace's equation
# 	@f[ \nabla^2 u = 0 @f]
# to smoothly replace missing values in two-dimensional NetCDF
# variables with the average of the ``nearby'' non-missing values.
#
# Here is hypothetical example, filling the missing values in the variables
# `topg` and `usurf` in `data.nc` :
# \code
# pism_fill_missing_petsc -v topg,usurf data.nc data_smoothed.nc
# \endcode
# Generally variables should be filled one at a time.
#
# Each of the requested variables must have missing values specified
# using the _FillValue attribute.

import petsc4py
import sys
petsc4py.init(sys.argv)

from petsc4py import PETSc
import numpy as np


def assemble_matrix(mask):
    """Assemble the matrix corresponding to the standard 5-point stencil
    approximation of the Laplace operator on the domain defined by
    mask == True, where mask is a 2D NumPy array.

    Uses zero Neumann BC at grid edges.

    The grid spacing is ignored, which is equivalent to assuming equal
    spacing in x and y directions.
    """
    PETSc.Sys.Print("Assembling the matrix...")
    # grid size
    nrow, ncol = mask.shape

    # create sparse matrix
    A = PETSc.Mat()
    A.create(PETSc.COMM_WORLD)
    A.setSizes([nrow * ncol, nrow * ncol])
    A.setType('aij')  # sparse
    A.setPreallocationNNZ(5)

    # precompute values for setting
    # diagonal and non-diagonal entries
    diagonal = 4.0
    offdx = - 1.0
    offdy = - 1.0

    def R(i, j):
        "Map from the (row,column) pair to the linear row number."
        return i * ncol + j

    # loop over owned block of rows on this
    # processor and insert entry values
    row_start, row_end = A.getOwnershipRange()
    for row in range(row_start, row_end):

        i = row // ncol    # map row number to
        j = row - i * ncol  # grid coordinates

        if mask[i, j] == False:
            A[row, row] = diagonal
            continue

        D = diagonal

        # i
        if i == 0:              # top row
            D += offdy

        if i > 0:               # interior
            col = R(i - 1, j)
            A[row, col] = offdx

        if i < nrow - 1:        # interior
            col = R(i + 1, j)
            A[row, col] = offdx

        if i == nrow - 1:       # bottom row
            D += offdy

        # j
        if j == 0:              # left-most column
            D += offdx

        if j > 0:               # interior
            col = R(i, j - 1)
            A[row, col] = offdy

        if j < ncol - 1:        # interior
            col = R(i, j + 1)
            A[row, col] = offdy

        if j == ncol - 1:       # right-most column
            D += offdx

        A[row, row] = D

    # communicate off-processor values
    # and setup internal data structures
    # for performing parallel operations
    A.assemblyBegin()
    A.assemblyEnd()

    PETSc.Sys.Print("done.")
    return A


def assemble_rhs(rhs, X):
    """Assemble the right-hand side of the system approximating the
    Laplace equation.

    Modifies rhs in place; sets Dirichlet BC using X where X.mask ==
    False.
    """
    # PETSc.Sys.Print("Setting Dirichlet BC...")
    nrow, ncol = X.shape
    row_start, row_end = rhs.getOwnershipRange()

    # The right-hand side is zero everywhere except for Dirichlet
    # nodes.
    rhs.set(0.0)

    for row in range(row_start, row_end):
        i = row // ncol    # map row number to
        j = row - i * ncol  # grid coordinates

        if X.mask[i, j] == False:
            rhs[row] = 4.0 * X[i, j]

    rhs.assemble()
    # PETSc.Sys.Print("done.")


def create_solver():
    "Create the KSP solver"
    # create linear solver
    ksp = PETSc.KSP()
    ksp.create(PETSc.COMM_WORLD)

    # Use algebraic multigrid:
    pc = ksp.getPC()
    pc.setType(PETSc.PC.Type.GAMG)
    ksp.setFromOptions()

    ksp.setInitialGuessNonzero(True)

    return ksp


def fill_missing(field, matrix=None):
    """Fill missing values in a NumPy array 'field' using the matrix
    'matrix' approximating the Laplace operator."""

    ksp = create_solver()

    if matrix is None:
        A = assemble_matrix(field.mask)
    else:
        # PETSc.Sys.Print("Reusing the matrix...")
        A = matrix

    # obtain solution & RHS vectors
    x, b = A.getVecs()

    assemble_rhs(b, field)

    initial_guess = np.mean(field)

    # set the initial guess
    x.set(initial_guess)

    ksp.setOperators(A)

    # Solve Ax = b
    # PETSc.Sys.Print("Solving...")
    ksp.solve(b, x)
    # PETSc.Sys.Print("done.")

    # transfer solution to processor 0
    vec0, scatter = create_scatter(x)
    scatter_to_0(x, vec0, scatter)

    return vec0, A


def create_scatter(vector):
    "Create the scatter to processor 0."
    comm = vector.getComm()
    rank = comm.getRank()
    scatter, V0 = PETSc.Scatter.toZero(vector)
    scatter.scatter(vector, V0, False, PETSc.Scatter.Mode.FORWARD)
    comm.barrier()

    return V0, scatter


def scatter_to_0(vector, vector_0, scatter):
    "Scatter a distributed 'vector' to 'vector_0' on processor 0 using 'scatter'."
    comm = vector.getComm()
    scatter.scatter(vector, vector_0, False, PETSc.Scatter.Mode.FORWARD)
    comm.barrier()


def scatter_from_0(vector_0, vector, scatter):
    "Scatter 'vector_0' on processor 0 to a distributed 'vector' using 'scatter'."
    comm = vector.getComm()
    scatter.scatter(vector, vector_0, False, PETSc.Scatter.Mode.REVERSE)
    comm.barrier()


def fill_2d_record(data, matrix=None):
    "Fill missing values in a 2D record."

    if getattr(data, "mask", None) is None:
        return data, None
    filled_data, A = fill_missing(data, matrix)
    if PETSc.COMM_WORLD.getRank() == 0:
        filled_data = filled_data[:].reshape(data.shape)

    return filled_data, A


def test():
    "Test fill_missing() using synthetic data."
    N = 201
    M = int(N * 1.5)
    x = np.linspace(-1, 1, N)
    y = np.linspace(-1, 1, M)
    xx, yy = np.meshgrid(x, y)
    zz = np.sin(2.5 * np.pi * xx) * np.cos(2.0 * np.pi * yy)

    K = 10
    mask = np.random.randint(0, K, zz.size).reshape(zz.shape) / float(K)

    mask[(xx - 1.0) ** 2 + (yy - 1.0) ** 2 < 1.0] = 1
    mask[(xx + 1.0) ** 2 + (yy + 1.0) ** 2 < 1.0] = 1

    field = np.ma.array(zz, mask=mask)

    zzz, _ = fill_missing(field)

    rank = PETSc.COMM_WORLD.getRank()
    if rank == 0:
        zzz0_np = zzz[:].reshape(field.shape)

        import pylab as plt

        plt.figure(1)
        plt.imshow(zz, interpolation='nearest')

        plt.figure(2)
        plt.imshow(field, interpolation='nearest')

        plt.figure(3)
        plt.imshow(zzz0_np, interpolation='nearest')

        plt.show()


def _get_fill(da):
    "Return _FillValue from attrs or encoding (xarray moves it after CF decoding)."
    return da.attrs.get("_FillValue", da.encoding.get("_FillValue"))


def _masked_view(da):
    """Return a 2D or 3D ``numpy.ma.array`` view of ``da``, masking entries
    equal to ``_FillValue`` (or ``missing_value`` as a fallback). Returns
    ``None`` if neither attribute is present."""
    fill = _get_fill(da)
    missing = da.attrs.get("missing_value", da.encoding.get("missing_value"))
    raw = np.asarray(da.values)
    if fill is None and missing is None:
        return None
    if fill is not None:
        mask = np.isclose(raw, fill)
    else:
        mask = np.isclose(raw, missing)
    return np.ma.array(raw, mask=mask)


def fill_variable(ds, name):
    "Fill missing values in one variable of an xarray Dataset (in place)."
    PETSc.Sys.Print("Processing %s..." % name)
    t0 = time()

    if name not in ds:
        PETSc.Sys.Print("Variable %s not found; skipping." % name)
        return

    da = ds[name]
    masked = _masked_view(da)
    if masked is None:
        PETSc.Sys.Print("Skipping %s: no _FillValue or missing_value attribute." % name)
        return

    comm = PETSc.COMM_WORLD
    rank = comm.getRank()

    raw = np.asarray(da.values)

    if masked.ndim == 3:
        A = None
        n_records = masked.shape[0]
        for t in range(n_records):
            PETSc.Sys.Print("Processing record %d/%d..." % (t + 1, n_records))
            slab = masked[t, :, :]
            filled_data, A = fill_2d_record(slab, A)
            if rank == 0:
                raw[t, :, :] = filled_data
            comm.barrier()
        PETSc.Sys.Print("Time elapsed: %5f seconds." % (time() - t0))
    elif masked.ndim == 2:
        filled_data, _ = fill_2d_record(masked)
        if rank == 0:
            raw[:, :] = filled_data
        comm.barrier()
        PETSc.Sys.Print("Time elapsed: %5f seconds." % (time() - t0))
    else:
        PETSc.Sys.Print("Skipping the %dD variable %s." % (masked.ndim, name))
        return

    if rank == 0:
        # Strip _FillValue / missing_value from both attrs and encoding so
        # they are not re-applied when the file is written out. Set
        # encoding["_FillValue"] = None explicitly so xarray does not
        # re-inject a default NaN fill value on serialization.
        new_attrs = dict(da.attrs)
        new_attrs.pop('_FillValue', None)
        new_attrs.pop('missing_value', None)
        new_encoding = dict(da.encoding)
        new_encoding['_FillValue'] = None
        new_encoding.pop('missing_value', None)
        new = xr.DataArray(raw, dims=da.dims, coords=da.coords,
                           attrs=new_attrs, name=da.name)
        new.encoding = new_encoding
        ds[name] = new


def add_history(ds):
    "Update the history attribute on an xarray Dataset (rank 0 only)."
    if PETSc.COMM_WORLD.getRank() != 0:
        return
    historystr = asctime() + ': ' + ' '.join(sys.argv) + '\n'
    if 'history' in ds.attrs:
        ds.attrs['history'] = historystr + ds.attrs['history']
    else:
        ds.attrs['history'] = historystr


if __name__ == "__main__":
    from argparse import ArgumentParser
    from time import time, asctime

    try:
        import xarray as xr
    except ImportError:
        PETSc.Sys.Print("xarray is not installed!")
        sys.exit(1)

    parser = ArgumentParser()
    parser.description = "Fill missing values by solving the Laplace equation in on the missing values and using present values as Dirichlet B.C."

    parser.add_argument("INPUT", nargs=1, help="Input file name.")
    parser.add_argument("OUTPUT", nargs=1, help="Output file name.")
    parser.add_argument("-a", "--all", dest="all", action="store_true",
                        help="Process all variables.")
    parser.add_argument("-v", "--vars", dest="variables",
                        help="comma-separated list of variables to process")

    options, _ = parser.parse_known_args()

    input_filename = options.INPUT[0]
    output_filename = options.OUTPUT[0]

    comm = PETSc.COMM_WORLD
    rank = comm.getRank()

    t0 = time()

    PETSc.Sys.Print("Filling missing values in %s and saving results to %s..."
                    % (input_filename, output_filename))

    try:
        # decode_cf=False keeps _FillValue/missing_value as raw attrs and the
        # data unmasked, so we can build our own masked view per variable.
        ds = xr.open_dataset(input_filename, decode_times=False,
                             decode_cf=False).load()
        ds.close()
    except Exception as message:
        PETSc.Sys.Print(str(message))
        PETSc.Sys.Print("Note: %s was not modified." % output_filename)
        sys.exit(-1)

    if options.all:
        variables = list(ds.data_vars)
    else:
        if not options.variables:
            PETSc.Sys.Print("Please specify variables using the -v option.")
            sys.exit(-1)
        variables = options.variables.split(',')

    add_history(ds)

    for name in variables:
        try:
            fill_variable(ds, name)
        except Exception as message:
            PETSc.Sys.Print("ERROR: %s" % message)
            PETSc.Sys.Print("Note: %s was not modified." % output_filename)
            sys.exit(-1)

    if rank == 0:
        try:
            ds.to_netcdf(output_filename, mode="w")
        except Exception as message:
            PETSc.Sys.Print("Error writing %s: %s. Exiting..."
                            % (output_filename, message))
            sys.exit(-1)
    comm.barrier()

    PETSc.Sys.Print("Total time elapsed: %5f seconds." % (time() - t0))
