#!/usr/bin/env python

from argparse import ArgumentParser
from netCDF4 import Dataset
import numpy as np
import matplotlib.pylab as pl
import seaborn as sns


def plot_layers(filename):
    df = Dataset(filename, "r")
    data = np.squeeze(df.variables["z"][:])
    # time = df.variables["time"]
    topg = np.squeeze(df.variables["topg"][:])[:]
    thk = np.squeeze(df.variables["thk"][:])[:]
    data=data + topg
    yi = df.variables["y"]
    xi = df.variables["x"]
    for y in xrange(topg.shape[-1]):
        f = pl.figure()
        f.set_size_inches([24,15])
        pl.plot(xi, data[:,:,y].transpose(), '.-')
        pl.plot(xi, thk[:,y]+topg[:,y], ':k')
        pl.plot(xi, topg[:,y], '--k')
        pl.title(yi[y])
        pl.ylim([-1000,4000])
        pl.savefig("slice%06d.png"%y)
        pl.close("all")

def parse_args():
  parser = ArgumentParser()
  parser.description = "compare slopes of two variables from two files"
  parser.add_argument("FILES", nargs='*')
  parser.add_argument("-v", "--verbose",
                    help='''Be verbose''', action="store_true")
  # parser.add_argument("-c", "--created_file",
  #                     help='''File with particle creation date and time''',
  #                     default = None)
  # parser.add_argument("-s", "--state",
  #                      help='''file with reference values''', required = True)
  # parser.add_argument("-b", "--var_b",
  #                    help='''variable b''', default="data")
  options = parser.parse_args()
  return options


def main():
    options = parse_args()
    if options.verbose:
        print (dir(options))
        print options.FILES
    [plot_layers(fn) for fn in options.FILES]

if __name__ == "__main__":
    main()
