#!/usr/bin/env python

import netCDF4
import sys
import matplotlib.pylab as mpl

def main (filenames):
    for f in filenames[::5]:
        ds=netCDF4.Dataset(f,'r')
        if not "x" in ds.variables.keys():
            print ("Couldn't find p_x in %s\n"%f)
            continue
        x=ds.variables["x"][:]
        y=ds.variables["y"][:]
        cx = ds.variables["x"][:]
        cy = ds.variables["y"][:]
        mpl.figure()
        print f 
        print x.shape
        print y.shape
        for (n, (ix, iy)) in enumerate(zip (x,y)):
            mpl.plot(ix,iy,'.')
            mpl.xlim((1.1*x.min(), 1.1*x.max()))
            mpl.ylim((1.1*y.min(), 1.1*y.max()))
            mpl.savefig(f[:-3]+"%06d.png"%n)
        mpl.close("all")
       

if __name__ == "__main__":
    
    main(sys.argv[1:])
    
