#!/usr/bin/ruby -w

# Copyright (C) 2004-2007 Jed Brown and Ed Bueler
#
# This file is part of Pism.
#
# Pism is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# Pism is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License
# along with Pism; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

cdl_input = 'pism_state.cdl'
c_source = 'ncgen.c'
c_attributes = 'write_attributes.c'

system("ncgen -v2 -c #{cdl_input} > #{c_source}")

s = File.new(c_source)
s.gets until $_ =~ /^main\(\)/

o = File.new(c_attributes, 'w')

o.puts ["// This file was automatically generated by `ncgen.rb' from",
        "// `pism_state.cdl'.  If you edit it, your changes will be overwritten",
        "// on the next invocation of `ncgen.rb'."]

s.each do |l|
  l.sub!(/91/, 'grid.p->Mx')
  l.sub!(/92/, 'grid.p->My')
  l.sub!(/93/, 'grid.p->Mz')
  l.sub!(/94/, '(grid.p->Mbz == 0 ? 1 : grid.p->Mbz)')
  l.sub!(/"pism_state.nc"/, 'fname')
  o << l
  if l =~ /enter define mode/ then o << "if (grid.rank == 0) {\n" end
  break if l =~ /nc_enddef/
end
o << s.gets << "} // end if (grid.rank == 0)\n"
o.close
