#!/bin/bash

# Runs the CCL3 EISMINT-Greenland experiment.  Requires GRIP ice core 
# temperature data in grip_dT.nc and SPECMAP sea bed core (stack) sea level
# data in specmap_dSL.nc; these are generated by eiscore.py.  Starts from a result
# of the SSL2 run.
#
# See the PISM User's Manual.
#
# A recommended way to run with 8 processors is "./ccl3.sh 8 >& out.ccl3 &"
# which saves a transcript in out.ccl3

NN=2  # default number of processors
if [ $# -gt 0 ] ; then  # if user says "ccl3.sh 8" then NN=8
  NN="$1"
fi

SHOW=
if [ $# -gt 1 ] ; then  # if user says "./ccl3.sh 8 D" then NN = 8 and *only* shows
                        #   what will happen; NO RUN (debug mode)
  SHOW="echo "
fi

set -e  # exit on error

MPIDO="mpiexec -n"

INFILE=green_ssl2_110ka.nc

DTFILE=grip_dT.nc
DSLFILE=specmap_dSL.nc
forcing="-atmosphere eismint_greenland,delta_T -ocean constant,delta_SL -atmosphere_delta_T_file $DTFILE -ocean_delta_SL_file $DSLFILE"

snaps="-save_file snaps_ccl3.nc -save_times -240000:10000:-10000"

ts="-ts_file ts_ccl3.nc -ts_times -249900:yearly:0"

PISM="pismr -sia_e 3 -calving ocean_kill -atmosphere eismint_greenland -surface pdd"

$SHOW $MPIDO $NN $PISM -bed_def lc -skip -skip_max 20 -i $INFILE -ocean_kill_file $INFILE -ys -249900 -ye 0 ${forcing} ${snaps} ${ts} -o green_ccl3_year0.nc

