name: Build a "base" container (dev branch)

on:
  push:
    branches: "dev"
    paths:
      - 'docker/pism/base/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for the "runtime" image
        id: meta-runtime
        uses: docker/metadata-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-runtime
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch,prefix=
            type=sha,format=short,prefix=

      - name: Build the "runtime" image
        id: build-and-push-runtime
        uses: docker/build-push-action@v7
        with:
          context: docker/pism/base/
          target: pism-runtime
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-runtime.outputs.tags }}
          labels: ${{ steps.meta-runtime.outputs.labels }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for the "base" image
        id: meta-base
        uses: docker/metadata-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-base
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch,prefix=
            type=sha,format=short,prefix=

      - name: Build the "base" image
        id: build-and-push-base
        uses: docker/build-push-action@v7
        with:
          context: docker/pism/base/
          target: pism-base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
