# Test installing PISM's dependencies using Homebrew and building PISM from sources
name: Dependencies using Homebrew, PISM from sources

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          brew update
          brew tap pism/pism
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install --only-dependencies pism
      - run: cmake -B build -S . \
          -DCMAKE_C_FLAGS="-Werror" \
          -DCMAKE_CXX_FLAGS="-Werror" \
          -DPism_BUILD_PYTHON_BINDINGS=YES \
          -DPism_USE_PARALLEL_NETCDF4=YES \
          -DPism_USE_YAC=YES \
          -DPism_USE_PROJ=YES
      - run: make -j4 -C build all
      - run: make -C build test
